/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachClientsRouteImport } from './routes/coach.clients'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScannerRouteImport } from './routes/app.scanner'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCalculatorRouteImport } from './routes/app.calculator'
import { Route as CoachClientsIdRouteImport } from './routes/coach.clients.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachClientsRoute = CoachClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => CoachRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorRoute = AppCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AppRoute,
} as any)
const CoachClientsIdRoute = CoachClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CoachClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/progress': typeof AppProgressRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/coach/clients': typeof CoachClientsRouteWithChildren
  '/coach/clients/$id': typeof CoachClientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/progress': typeof AppProgressRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/coach/clients': typeof CoachClientsRouteWithChildren
  '/coach/clients/$id': typeof CoachClientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/calculator': typeof AppCalculatorRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/progress': typeof AppProgressRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/coach/clients': typeof CoachClientsRouteWithChildren
  '/coach/clients/$id': typeof CoachClientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/coach'
    | '/onboarding'
    | '/app/calculator'
    | '/app/dashboard'
    | '/app/progress'
    | '/app/scanner'
    | '/app/settings'
    | '/coach/clients'
    | '/coach/clients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/coach'
    | '/onboarding'
    | '/app/calculator'
    | '/app/dashboard'
    | '/app/progress'
    | '/app/scanner'
    | '/app/settings'
    | '/coach/clients'
    | '/coach/clients/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/coach'
    | '/onboarding'
    | '/app/calculator'
    | '/app/dashboard'
    | '/app/progress'
    | '/app/scanner'
    | '/app/settings'
    | '/coach/clients'
    | '/coach/clients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CoachRoute: typeof CoachRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/clients': {
      id: '/coach/clients'
      path: '/clients'
      fullPath: '/coach/clients'
      preLoaderRoute: typeof CoachClientsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scanner': {
      id: '/app/scanner'
      path: '/scanner'
      fullPath: '/app/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calculator': {
      id: '/app/calculator'
      path: '/calculator'
      fullPath: '/app/calculator'
      preLoaderRoute: typeof AppCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/coach/clients/$id': {
      id: '/coach/clients/$id'
      path: '/$id'
      fullPath: '/coach/clients/$id'
      preLoaderRoute: typeof CoachClientsIdRouteImport
      parentRoute: typeof CoachClientsRoute
    }
  }
}

interface AppRouteChildren {
  AppCalculatorRoute: typeof AppCalculatorRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProgressRoute: typeof AppProgressRoute
  AppScannerRoute: typeof AppScannerRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalculatorRoute: AppCalculatorRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProgressRoute: AppProgressRoute,
  AppScannerRoute: AppScannerRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CoachClientsRouteChildren {
  CoachClientsIdRoute: typeof CoachClientsIdRoute
}

const CoachClientsRouteChildren: CoachClientsRouteChildren = {
  CoachClientsIdRoute: CoachClientsIdRoute,
}

const CoachClientsRouteWithChildren = CoachClientsRoute._addFileChildren(
  CoachClientsRouteChildren,
)

interface CoachRouteChildren {
  CoachClientsRoute: typeof CoachClientsRouteWithChildren
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachClientsRoute: CoachClientsRouteWithChildren,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CoachRoute: CoachRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
